services:
  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      remusgold-net:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:8000"
    depends_on:
      - db
    volumes:
      - ./media/:/code/media
      - ./static/:/code/static
      - ./remusgold/account:/code/remusgold/account
      - ./remusgold/payments:/code/remusgold/payments
      - ./remusgold/store:/code/remusgold/store
      - ./remusgold/vouchers:/code/remusgold/vouchers
      - ./remusgold/transfers:/code/remusgold/transfers

    networks:
      remusgold-net:
  
networks:
  remusgold-net:
