services:
  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      remusgold-net:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:8000"
    depends_on:
      - db
    volumes:
      - ./media/:/code/media
      - ./static/:/code/static
      - ./remusgold/account:/code/remusgold/account
      - ./remusgold/payments:/code/remusgold/payments
      - ./remusgold/store:/code/remusgold/store
      - ./remusgold/vouchers:/code/remusgold/vouchers
      - ./remusgold/transfers:/code/remusgold/transfers
      - ./remusgold/rates:/code/remusgold/rates
    networks:
      remusgold-net:
  receiver:
    build:
      context: .
      dockerfile: dockerfiles/receiver.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      remusgold-net:
  rates_checker:
    build:
      context: .
      dockerfile: dockerfiles/rates_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      remusgold-net:
  gold_checker:
    build:
      context: .
      dockerfile: dockerfiles/gold_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      remusgold-net:
  lottery_checker:
    build:
      context: .
      dockerfile: dockerfiles/lottery_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      remusgold-net:
  invoice_checker:
    build:
      context: .
      dockerfile: dockerfiles/invoice_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      remusgold-net:
  scanner:
    build:
      context: .
      dockerfile: dockerfiles/scanner.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      remusgold-net:
    volumes:
      - ./scanner/settings:/code/scanner/settings
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env
    restart: unless-stopped
    networks:
      remusgold-net:
  
networks:
  remusgold-net:
