# Generated by Django 3.1.6 on 2021-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='btc_address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advuser',
            name='eth_address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
