# Generated by Django 3.1.6 on 2021-02-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210215_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='fixed_btc_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=78),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fixed_eth_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=78),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fixed_usdc_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=78),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='received_usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order'),
            preserve_default=False,
        ),
    ]
