# Generated by Django 3.1.6 on 2021-02-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210216_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fixed_btc_rate',
            field=models.DecimalField(decimal_places=8, max_digits=78, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fixed_eth_rate',
            field=models.DecimalField(decimal_places=8, max_digits=78, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fixed_usdc_rate',
            field=models.DecimalField(decimal_places=8, max_digits=78, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='payments.order'),
            preserve_default=False,
        ),
    ]
