# Generated by Django 3.1.5 on 2021-01-27 08:20

from django.db import migrations, models
import django.db.models.deletion
import remusgold.store.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('images', models.ImageField(blank=True, upload_to=remusgold.store.utilities.get_timestamp_path)),
                ('total_supply', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('price', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.group')),
            ],
        ),
    ]
