# Generated by Django 3.1.6 on 2021-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsdRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=78)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
