# Generated by Django 3.1.6 on 2021-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=78)),
                ('currency', models.CharField(max_length=10)),
                ('duc_address', models.CharField(max_length=50)),
                ('tx_hash', models.CharField(max_length=100)),
                ('tx_error', models.TextField(default='')),
                ('status', models.CharField(default='WAITING FOR TRANSFER', max_length=50)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
